repos:
  - repo: local
    hooks:
      # - id: check-hardcoded-strings
      #   name: Check for hardcoded strings
      #   entry: ./scripts/check-hardcoded-strings.sh
      #   language: script
      #   types: [rust]
      #   exclude: |
      #     (?x)^(
      #       tests/.*|
      #       benches/.*|
      #       examples/.*
      #     )$
      - id: cargo-fmt
        name: Cargo Format
        entry: cargo fmt --all --verbose
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: Cargo Check
        entry: cargo check --all-features
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test
        name: Cargo Test
        entry: cargo test --all-features
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: Cargo Clippy
        entry: cargo clippy --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
