# Rust formatting configuration
# See https://rust-lang.github.io/rustfmt/

# Basic formatting
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Code organization
reorder_modules = true
merge_derives = true

# Comments and documentation
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100

# Function formatting
fn_args_layout = "Tall"
fn_single_line = false
where_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true

# Struct and enum formatting
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

# Advanced settings
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true 