services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../Cargo.toml:/app/Cargo.toml
      - ../Cargo.lock:/app/Cargo.lock
      - ../config/config.dev.toml:/app/config.toml
    ports:
      - "${SERVER_BACKEND_PORT:-3333}:${SERVER_BACKEND_PORT:-3333}"
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=${LOGGING_LEVEL:-debug}
      - DEFAULT_LANGUAGE=${SERVER_DEFAULT_LANGUAGE:-en}
      - CONFIG_FILE=/app/config.toml
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    command: redis-server ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}} --bind 0.0.0.0
    environment:
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
