services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "${SERVER_BACKEND_PORT:-3333}:${SERVER_BACKEND_PORT:-3333}"
    environment:
      - RUST_BACKTRACE=0
      - RUST_LOG=${LOGGING_LEVEL:-info}
      - DEFAULT_LANGUAGE=${SERVER_DEFAULT_LANGUAGE:-en}
      - CONFIG_FILE=/app/config.toml
    volumes:
      - ../config/config.prod.toml:/app/config.toml
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_BACKEND_PORT:-3333}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0
    environment:
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    secrets:
      - redis_password
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

secrets:
  db_password:
    external: true
  redis_password:
    external: true

networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: "true" 