services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=${LOGGING_LEVEL:-debug}
      - CONFIG_FILE=/app/config.toml
      - TEST_COVERAGE=true
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-acci}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-acci-backend}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET:-test_secret}
    volumes:
      - ../config/config.test.toml:/app/config.toml
      - ../target/coverage:/app/target/coverage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/${KEYCLOAK_DB_NAME:-keycloak}
      - KC_DB_USERNAME=${DATABASE_USER:-acci}
      - KC_DB_PASSWORD=${DATABASE_PASSWORD:-acci}
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    tmpfs:
      - /opt/keycloak/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-acci}
      - POSTGRES_USER=${DATABASE_USER:-acci}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-acci}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DATABASE_USER:-acci}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    command: redis-server ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}} --bind 0.0.0.0
    environment:
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    tmpfs:
      - /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  security-scan:
    image: aquasec/trivy:latest
    volumes:
      - ../:/app
    command: ["fs", "--security-checks", "vuln,config", "--severity", "HIGH,CRITICAL", "/app"]

  test-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    command: ["cargo", "test", "--all-features", "--workspace"]
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=${LOGGING_LEVEL:-debug}
      - CONFIG_FILE=/app/config.toml
      - TEST_COVERAGE=true
    volumes:
      - ../config/config.test.toml:/app/config.toml
      - ../target/coverage:/app/target/coverage
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
