# Test Environment Configuration

[server]
backend_port = 3333
default_language = "en"

[database]
host = "db"
port = 5432
name = "acci"
user = "acci"
password = "acci"
max_connections = 10
min_connections = 2
connect_timeout = 5
acquire_timeout = 5
idle_timeout = 60
max_lifetime = 300

[redis]
url = "redis://localhost:6379"

[logging]
level = "debug"

[keycloak]
url = "http://keycloak:8080/auth"
realm = "acci"
client_id = "acci-backend"
client_secret = "test_secret"
admin_username = "admin"
admin_password = "admin"
verify_token = true
public_key_cache_ttl = 3600 # 1 hour in seconds
