# Test Environment Configuration

[server]
backend_port = 3333
default_language = "en"

[database]
host = "db"
port = 5432
name = "acci"
user = "acci"
password = "acci"

[redis]
url = "redis://localhost:6379"

[logging]
level = "debug"
