# Test Environment Configuration

[server]
backend_port = 3333
default_language = "en"

[database]
host = "db"
port = 5432
name = "acci_test"
user = "acci"
password = "acci"
max_connections = 10
connection_timeout = 5
idle_timeout = 60

[redis]
url = "redis://redis:6379"
pool_size = 5
max_connections = 10
connection_timeout = 5

[logging]
level = "debug"
format = "pretty"
output = "stdout"
request_logging = true
error_logging = true
performance_logging = false

[keycloak]
url = "http://keycloak:8080/auth"
realm = "acci-test"
client_id = "acci-test"
client_secret = "acci_test_secret"
admin_username = "admin"
admin_password = "admin"
verify_token = true
public_key_cache_ttl = 300

[eventstore]
connection_string = "esdb://eventstore:2113?tls=false"
username = "admin"
password = "changeit"
max_retries = 3
retry_delay = 500
snapshot_interval = 50
max_append_size = "1MB"

[rabbitmq]
url = "amqp://acci:acci@rabbitmq:5672"
connection_pool_size = 5
channels_per_connection = 5
prefetch_count = 50
message_ttl = 3600000
dead_letter_enabled = true

[testing]
coverage_enabled = true
coverage_output_dir = "/app/target/coverage"
parallel_tests = true
test_timeout = 30
retry_failed_tests = true
max_retries = 3

[security]
enable_cors = true
allowed_origins = ["*"]
rate_limit = false
enable_csrf = false
secure_headers = false

[monitoring]
metrics_enabled = true
metrics_path = "/metrics"
tracing_enabled = true
health_check_interval = 5
health_check_timeout = 2
