global:
  resolve_timeout: 5m
  smtp_from: '{{ env "SMTP_USER" }}'
  smtp_smarthost: '{{ env "SMTP_HOST" }}:{{ env "SMTP_PORT" }}'
  smtp_auth_username: '{{ env "SMTP_USER" }}'
  smtp_auth_password: '{{ env "SMTP_PASSWORD" }}'
  smtp_require_tls: true
  xmpp_from: '{{ env "XMPP_USER" }}'
  xmpp_password: '{{ env "XMPP_PASSWORD" }}'
  xmpp_server: '{{ env "XMPP_SERVER" }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-ops'
  routes:
    - match:
        severity: critical
      receiver: 'team-ops-urgent'
      repeat_interval: 1h
      continue: true
    - match:
        severity: warning
      receiver: 'team-ops'
      continue: true
    - match_re:
        service: ^(tenant|user).*
      receiver: 'team-business'
    - match_re:
        service: ^(auth|security).*
      receiver: 'team-security'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'team-ops'
    email_configs:
      - to: 'ops@acci.io'
        send_resolved: true
    slack_configs:
      - api_url: '{{ env "SLACK_WEBHOOK_URL" }}'
        channel: '#ops-alerts'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    xmpp_configs:
      - to: 'ops-alerts@xmpp.acci.io'
        send_resolved: true
        text: '{{ template "jabber.message" . }}'

  - name: 'team-ops-urgent'
    email_configs:
      - to: 'ops-urgent@acci.io'
        send_resolved: true
    slack_configs:
      - api_url: '{{ env "SLACK_WEBHOOK_URL" }}'
        channel: '#ops-urgent'
        send_resolved: true
        title: '[CRITICAL] {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    webhook_configs:
      - url: '{{ env "TEAMS_WEBHOOK_URL" }}'
        send_resolved: true
    xmpp_configs:
      - to: 'ops-urgent@xmpp.acci.io'
        send_resolved: true
        text: '[CRITICAL] {{ template "jabber.message" . }}'
        priority: high

  - name: 'team-business'
    email_configs:
      - to: 'business@acci.io'
        send_resolved: true
    slack_configs:
      - api_url: '{{ env "SLACK_WEBHOOK_URL" }}'
        channel: '#business-alerts'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    xmpp_configs:
      - to: 'business-alerts@xmpp.acci.io'
        send_resolved: true
        text: '{{ template "jabber.message" . }}'

  - name: 'team-security'
    email_configs:
      - to: 'security@acci.io'
        send_resolved: true
    slack_configs:
      - api_url: '{{ env "SLACK_WEBHOOK_URL" }}'
        channel: '#security-alerts'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    xmpp_configs:
      - to: 'security-alerts@xmpp.acci.io'
        send_resolved: true
        text: '{{ template "jabber.message" . }}' 