global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - 'rules/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  - job_name: 'acci-app'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'tasks.app'
        type: 'A'
        port: 3333

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'tasks.rabbitmq'
        type: 'A'
        port: 15692

  - job_name: 'redis'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'tasks.redis'
        type: 'A'
        port: 9121

  - job_name: 'postgres'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'tasks.db'
        type: 'A'
        port: 9187

  - job_name: 'eventstore'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    dns_sd_configs:
      - names:
        - 'tasks.eventstore'
        type: 'A'
        port: 2113 